[package]
name = "holz_logistik_server"
version = "0.1.0"
edition = "2024"
authors = ["Josef Draexl <info@draexl-it.com>"]
description = "Real-time synchronization server for the Holz Logistik app"

[dependencies]
# Web framework
tokio = { version = "1.35", features = ["full"] }
axum = { version = "0.8.3", features = ["ws"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }

# WebSocket
futures = "0.3"
futures-util = "0.3"

# Database
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "sqlite", "time", "macros"] }

# Authentication
jsonwebtoken = "9.2"
argon2 = "0.5"

# Utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
thiserror = "2.0.12"
anyhow = "1.0"
rand = "0.9.0"
async-trait = "0.1"
once_cell = "1.19"