[package]
name = "db_test"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = "0.35.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
chrono = "0.4.40"
uuid = { version = "1.3", features = ["v4"] }
base64 = "0.22.1"
